[general]
live_config_reload = true

import = [
   "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "alacritty"

[font]
size = 15.0

[font.bold]
family = "Office Code Pro"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[keyboard]
bindings = [
   # These are all the bash shortcuts that use alt but because this is a mac we need to use super and pass create this binding to pass them to the shell
   # The bash shortcuts that use ctrl seem to work fine
   { key = "B", mods = "Super", chars = "\u001bb" },
   { key = "F", mods = "Super", chars = "\u001bf" },
   { key = "D", mods = "Super", chars = "\u001bd" },
   { key = "=", mods = "Control", action = "IncreaseFontSize" },
   { key = "-", mods = "Control", action = "DecreaseFontSize" },
   { key = "0", mods = "Control", action = "ResetFontSize" },
]
