live_config_reload = true

import = [
   "${PWD}/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "alacritty"

[font]
size = 15.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
