#!/bin/bash

# Adjusts the brightness
# $1: up(+) or down(-)
#
function adjust_brightness() {
    actual_brightness=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
    max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

    let "step_size = $max_brightness / 30"

    if [[ $1 == "+" || $1 == "up" ]]; then
        let "next_brightness = $actual_brightness + $step_size"
        if [[ $next_brightness -gt $max_brightness ]]; then
            next_brightness=$max_brightness
        fi
    else
        let "next_brightness = $actual_brightness - $step_size"
        if [[ $next_brightness -lt 0 ]]; then
            next_brightness=0
        fi
    fi

    echo $next_brightness > '/sys/class/backlight/intel_backlight/brightness'
}


# Sanity check of inputs
if [[ $1 == "+" || $1 == "up" || $1 == "-" || $1 == "down" ]]; then
    adjust_brightness $1
else
    exit 1
fi
